sudo: false
language: java
after_success:
  - mvn clean test jacoco:report coveralls:report
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
matrix:
  # OpenJDK 11 might fail for now. We need to update several maven plugins to make
  # it run successfully.
  allow_failures:
    - jdk: openjdk11
